"""empty message

Revision ID: 016d13a4d3fc
Revises: 714930acb147
Create Date: 2019-11-22 11:16:15.499210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '016d13a4d3fc'
down_revision = '714930acb147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clicks_post_id', table_name='clicks')
    op.drop_table('clicks')
    op.add_column('post_actions', sa.Column('ctr', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_actions', 'ctr')
    op.create_table('clicks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='clicks_post_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='clicks_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='clicks_pkey')
    )
    op.create_index('ix_clicks_post_id', 'clicks', ['post_id'], unique=False)
    # ### end Alembic commands ###
