"""empty message

Revision ID: 3eba9f786ead
Revises: 75fa42054d36
Create Date: 2019-11-22 12:35:42.512014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3eba9f786ead'
down_revision = '75fa42054d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('joblock', sa.Column('job_type', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'joblock', ['job_type'])
    op.create_foreign_key(None, 'joblock', 'job_types', ['job_type'], ['id'], ondelete='CASCADE')
    op.drop_column('joblock', 'job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('joblock', sa.Column('job', postgresql.ENUM('COLLECT', 'PROCESS', 'RELATE', name='jobs'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'joblock', type_='foreignkey')
    op.drop_constraint(None, 'joblock', type_='unique')
    op.drop_column('joblock', 'job_type')
    op.drop_table('job_types')
    # ### end Alembic commands ###
