"""empty message

Revision ID: 6f5bfc08b917
Revises: c0d2b8ed6574
Create Date: 2020-01-16 18:53:10.077924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5bfc08b917'
down_revision = 'c0d2b8ed6574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_queue')
    op.drop_index('ix_entities_post_id', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='entities_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='entities_pkey')
    )
    op.create_index('ix_entities_post_id', 'entities', ['post_id'], unique=False)
    op.create_table('entity_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='entity_queue_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='entity_queue_pkey'),
    sa.UniqueConstraint('post_id', name='entity_queue_post_id_key')
    )
    # ### end Alembic commands ###
