"""empty message

Revision ID: 9b15f87d0a61
Revises: 9c2ad940ed4e
Create Date: 2019-12-14 15:29:14.175552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b15f87d0a61'
down_revision = '9c2ad940ed4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('action_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_views_post_id'), 'post_views', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_views_user_id'), 'post_views', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_views_user_id'), table_name='post_views')
    op.drop_index(op.f('ix_post_views_post_id'), table_name='post_views')
    op.drop_table('post_views')
    # ### end Alembic commands ###
