"""empty message

Revision ID: 9c2ad940ed4e
Revises: 8d1fc0608a4f
Create Date: 2019-11-25 21:31:38.410312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2ad940ed4e'
down_revision = '8d1fc0608a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_index(op.f('ix_user_email'), table_name='user')
    # ### end Alembic commands ###
