"""empty message

Revision ID: b20a1484c41d
Revises: 29f630184cdb
Create Date: 2020-02-12 19:29:49.492448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20a1484c41d'
down_revision = '29f630184cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_statuses', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_statuses', 'active')
    # ### end Alembic commands ###
