"""empty message

Revision ID: b20a1484c41d
Revises: 29f630184cdb
Create Date: 2020-02-12 19:29:49.492448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20a1484c41d'
down_revision = '29f630184cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similarities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_similarities_source_id'), 'similarities', ['source_id'], unique=False)
    op.create_table('similarity_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.add_column('feed_statuses', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_statuses', 'active')
    op.drop_table('similarity_queue')
    op.drop_index(op.f('ix_similarities_source_id'), table_name='similarities')
    op.drop_table('similarities')
    # ### end Alembic commands ###
