"""empty message

Revision ID: c0d2b8ed6574
Revises: 9b15f87d0a61
Create Date: 2019-12-24 13:25:32.669990

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_searchable import sync_trigger


# revision identifiers, used by Alembic.
revision = 'c0d2b8ed6574'
down_revision = '9b15f87d0a61'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_posts_search_vector', 'posts', ['search_vector'], unique=False, postgresql_using='gin')

    sync_trigger(conn, 'posts', 'search_vector', ['title', 'desc'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_search_vector', table_name='posts')
    op.drop_column('posts', 'search_vector')
    # ### end Alembic commands ###
